export const sidebarLinks = [
  {
    imgURL: "/assets/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/assets/dish-svgrepo-com.svg",
    route: "/others",
    label: "Others",
  },
  {
    imgURL: "/assets/couple-of-men-drinking-in-a-bar-svgrepo-com.svg",
    route: "/users",
    label: "Users",
  },
  {
    imgURL: "/assets/heart.svg",
    route: "/activity",
    label: "Activity",
  },
  {
    imgURL: "/assets/create.svg",
    route: "/create-thread",
    label: "Create Post",
  },
  {
    imgURL: "/assets/community.svg",
    route: "/communities",
    label: "Communities",
  },
  {
    imgURL: "/assets/user.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/assets/search.svg",
    route: "/search",
    label: "Search",
  },
  {
    imgURL: "/assets/favorites-star-svgrepo-com.svg",
    route: "/favorites",
    label: "Favorites",
  },
];

export const profileTabs = [
  { value: "posts", label: "Posts", icon: "/assets/reply.svg" },
  // {
  //   value: "Reviews",
  //   label: "Reviews",
  //   icon: "/assets/review-svgrepo-com.svg",
  // },
];

export const communityTabs = [
  { value: "threads", label: "Threads", icon: "/assets/reply.svg" },
  { value: "members", label: "Members", icon: "/assets/members.svg" },
  { value: "requests", label: "Requests", icon: "/assets/request.svg" },
];

export const allIngredients = [
  { label: "Ash gourd", value: "Ash gourd" },
  { label: "Broccoli", value: "Broccoli" },
  { label: "Cucumber", value: "Cucumber" },
  { label: "Celery", value: "Celery" },
  { label: "Bitter Gourd", value: "Bitter Gourd" },
  { label: "Elephant Yam", value: "Elephant Yam" },
  { label: "Carrot", value: "Carrot" },
  { label: "Spring Onion", value: "Spring Onion" },
  { label: "Potato", value: "Potato" },
  { label: "Capsicum", value: "Capsicum" },
  { label: "Turnip", value: "Turnip" },
  { label: "Brinjal", value: "Brinjal" },
  { label: "Cluster Beans", value: "Cluster Beans" },
  { label: "Green Peas", value: "Green Peas" },
  { label: "Onio", value: "Onio" },
  { label: "Apple Gourd", value: "Apple Gourd" },
  { label: "Onion", value: "Onion" },
  { label: "Cauliflower", value: "Cauliflower" },
  { label: "Cabbage", value: "Cabbage" },
  { label: "Beetroot", value: "Beetroot" },
  { label: "Ridge Gourd", value: "Ridge Gourd" },
  { label: "Garlic", value: "Garlic" },
  { label: "Chow Chow", value: "Chow Chow" },
  { label: "Mushroom", value: "Mushroom" },
  { label: "Lady Finger", value: "Lady Finger" },
  { label: "Snake Gourd", value: "Snake Gourd" },
  { label: "Ivy Gourd", value: "Ivy Gourd" },
  { label: "Spinach", value: "Spinach" },
  { label: "Beans", value: "Beans" },
  { label: "Lab Lab", value: "Lab Lab" },
  { label: "Green Papaya", value: "Green Papaya" },
  { label: "Corn", value: "Corn" },
  { label: "Pumpkin", value: "Pumpkin" },
  { label: "Bottle Gourd", value: "Bottle Gourd" },
  { label: "Snake Beans", value: "Snake Beans" },
  { label: "Drumstick", value: "Drumstick" },
  { label: "White Pumpkin", value: "White Pumpkin" },
  { label: "Radish", value: "Radish" },
  { label: "Field Beans / Broad Beans", value: "Field Beans / Broad Beans" },
  { label: "Zucchini", value: "Zucchini" },
  { label: "Celeriac", value: "Celeriac" },
  { label: "Sugar beet", value: "Sugar beet" },
  { label: "Horseradish", value: "Horseradish" },
  { label: "Parsnip", value: "Parsnip" },
  { label: "Rutabaga/Swede", value: "Rutabaga/Swede" },
  { label: "Mint", value: "Mint" },
  { label: "Mustard Green", value: "Mustard Green" },
  { label: "Coriander Leave", value: "Coriander Leave" },
  { label: "Arugula", value: "Arugula" },
  { label: "Lettuce", value: "Lettuce" },
  { label: "Bok Choy", value: "Bok Choy" },
  { label: "Rapini", value: "Rapini" },
  { label: "Kale", value: "Kale" },
  { label: "Lemon grass", value: "Lemon grass" },
  { label: "Asparagus", value: "Asparagus" },
  { label: "Kohlrabi", value: "Kohlrabi" },
  { label: "Celtuce", value: "Celtuce" },
  { label: "Rhubarb", value: "Rhubarb" },
  { label: "Swiss chard", value: "Swiss chard" },
  { label: "Cardoon", value: "Cardoon" },
  { label: "Artichoke", value: "Artichoke" },
  { label: "Banana Flower", value: "Banana Flower" },
  { label: "Zucchini Flower", value: "Zucchini Flower" },
  { label: "Leek", value: "Leek" },
  { label: "Fennel", value: "Fennel" },
  { label: "Ginger", value: "Ginger" },
  { label: "Turmeric", value: "Turmeric" },
  { label: "Chinese Potato", value: "Chinese Potato" },
  { label: "Arrowroot", value: "Arrowroot" },
  { label: "Tapioca", value: "Tapioca" },
  { label: "Greater yam", value: "Greater yam" },
  { label: "Purple yam", value: "Purple yam" },
  { label: "Peppers", value: "Peppers" },
  { label: "Eggplant", value: "Eggplant" },
  { label: "String beans", value: "String beans" },
  { label: "Lady’s finger", value: "Lady’s finger" },
  { label: "Chickpeas", value: "Chickpeas" },
];
